default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quick_build_development

test:
  <<: *default
  database: quick_build_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  # Estas tres usan la misma base, pero guardan migraciones en carpetas separadas.
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
